# Generated by Django 3.2.6 on 2021-09-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0007_alter_good_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='update_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
