# Generated by Django 3.2.6 on 2021-12-29 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_auto_20210918_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='good',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ship.category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ship.post'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='delivery_point',
        ),
        migrations.AddField(
            model_name='post',
            name='delivery_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='ship.place'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='receipt_point',
        ),
        migrations.AddField(
            model_name='post',
            name='receipt_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='ship.place'),
        ),
    ]
