# Generated by Django 3.2.6 on 2021-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0010_auto_20211229_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shipper',
            field=models.BooleanField(default=True),
        ),
    ]
