# Generated by Django 3.2.6 on 2021-12-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0012_alter_user_is_shipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_shipper',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
