# Generated by Django 3.2.6 on 2021-12-29 19:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0013_auto_20211229_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 29, 19, 13, 4, 513088, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper', to=settings.AUTH_USER_MODEL),
        ),
    ]
